### ISSUE TITLE
`ag3.snp_allele_frequencies()` still causing "PerformanceWarning: DataFrame is highly fragmented."

### ISSUE THREAD

**Issue by cclarkson** [malariagen/malariagen-data-python#107]
Either have `ag3.releases` return a tuple or allow `sample_set` parameter to accept list.

**Comment by alimanfoo** [comment]
Hi @cclarkson, can you give a MRE where you think things are currently breaking? 

(I thought as things currently stand, `ag3.releases` is a tuple, and all methods which take a `sample_sets` parameter can accept either a list or a tuple.)

**Comment by cclarkson** [comment]
Hi Alistair, 

Ignore me! All is well.
