### ISSUE TITLE
Inconsistency in array lengths before and after computation

### ISSUE THREAD

**Issue by alimanfoo** [malariagen/malariagen-data-python#114]
See example below, where results are different when run with different binder environments. These different environments may contain different versions of the malariagen_data package, but it is still surprising that results change for this particular situation.

![image](https://user-images.githubusercontent.com/703554/147354094-c3ff2bea-d5b4-4661-999e-9d685d516e7f.png)

![image](https://user-images.githubusercontent.com/703554/147354114-7ee29632-00f2-4647-aa5a-6aac6c3f49f8.png)

**Comment by cclarkson** [comment]
I can also reproduce this, it occurs in binders v3.1 - v3.5.

**Comment by alimanfoo** [comment]
Thanks @cclarkson.

Mapping package versions...

* binder v3.0.0 has malariagen_data v0.8.0
* binder v3.1.0 has malariagen_data v0.9.0
* binder v3.2.0 has malariagen_data v0.11.0
* binder v3.3.0 has malariagen_data v0.15.0

If this difference occurs between binder v3.0 and v3.1, then it would be good to investigate changes in malariagen_data betwee v0.8 and v0.9.

**Comment by alimanfoo** [comment]
Confirmed via colab, manually installing different versions of malariagen_data, change occurs between 0.8 and 0.9.

**Comment by cclarkson** [comment]
I looked at where the array is being truncated.
-2L - 32.96% of the array is what you get after `pos.compute()`
-2R - 40.27%
-3L - 32.92%
-3R - 40.25%
-X - 41.21

**Comment by cclarkson** [comment]
chunks="native" is the only difference I see that might have something to do with it?

**Comment by alimanfoo** [comment]
> chunks="native" is the only difference I see that might have something to do with it?

Yeah, I think that is the key difference. Why it makes a difference is tricky to see, but it points to a bug in the `da_compress` function. In general dask should never behave this way, where the array shape is different before and after computation. But the `da_compress` function is something I wrote that hacks some of the dask internals, which is a dangerous thing to do and could reasonably explain why this happens. Lesson - be very very careful when hacking dask internals!

**Comment by alimanfoo** [comment]
Kudos to @randomxsk8 for the original bug report.

**Comment by randomxsk8** [comment]
Thank you! :)
