### ISSUE TITLE
Interactive map weirdness

### ISSUE THREAD

**Issue by alimanfoo** [malariagen/malariagen-data-python#208]
Trying to use the `Ag3.plot_frequencies_interactive_map()` function I'm getting weirdness. For some reason I can't seem to get the `center` parameter to work as expected, when zoomed in a bit more. Suspect the addition and changes of markers are affecting this somehow. E.g., sometimes the map will jump to a new center when the selection of variant is changed.

**Comment by leehart** [comment]
I think we need a reproducible example, if possible.
For what it's worth, I haven't been able to reproduce any weirdness on Colab yet, using v7.3.0 with just the `center` and `zoom` params, but importantly: I haven't tried adding and changing markers yet, which sounds like the trigger.

Some basic notes on the params for this issue:

Our docs:
```
center : tuple of int, optional
    Location to center the map.
zoom : int, optional
    Initial zoom level.
```
(American English spelling of "center".)


Our defaults:
```
center=(-2, 20),
zoom=3,
```

Our pass-through:
```
freq_map = ipyleaflet.Map(center=center, zoom=zoom)
```


The `ipyleaflet` docs from https://ipyleaflet.readthedocs.io/en/latest/map_and_basemaps/map.html#ipyleaflet.Map.center
```
center
    The current center of the map.
    Type
        list, default [0, 0]

zoom
    The current zoom value of the map.
    Type
        float, default 12
```

**Comment by leehart** [comment]
I think I've found a potential source/explanation for the weirdness, although I haven't verified it yet.
The code for creating the interactive map widget does not maintain the state all of the function's parameters, including `center` and `zoom`.

I'll try changing this:
```
controls = ipywidgets.interactive(
    self.plot_frequencies_map_markers,
    m=ipywidgets.fixed(freq_map),
    ds=ipywidgets.fixed(ds),
    variant=ipywidgets.Dropdown(options=variants, description="Variant: "),
    taxon=ipywidgets.Dropdown(options=taxa, description="Taxon: "),
    period=ipywidgets.Dropdown(options=periods, description="Period: "),
    clear=ipywidgets.fixed(True),
)
```
To this:
```
controls = ipywidgets.interactive(
    self.plot_frequencies_map_markers,
    m=ipywidgets.fixed(freq_map),
    ds=ipywidgets.fixed(ds),
    center=ipywidgets.fixed(center),
    zoom=ipywidgets.fixed(zoom),
    title=ipywidgets.fixed(title),
    epilogue=ipywidgets.fixed(epilogue),
    variant=ipywidgets.Dropdown(options=variants, description="Variant: "),
    taxon=ipywidgets.Dropdown(options=taxa, description="Taxon: "),
    period=ipywidgets.Dropdown(options=periods, description="Period: "),
    clear=ipywidgets.fixed(True),
)
```

**Comment by leehart** [comment]
Is anyone able to confirm whether this is still happening, and provide some kind of demo with code?

**Comment by leehart** [comment]
I suspect this is because the map adjusts to the latest marker (or more specifically its "popup") that was added, i.e. it centres the map as instructed (at first) but then it automatically pans to show the added marker/popup. There is a `auto_pan=False` setting that might prevent this, but needs investigation.

Colab notebook with code to reproduce: https://colab.research.google.com/drive/1rJzYOXvfLhFSiFjOFcnhWhc8cbFRRRf2?usp=sharing

Potentially related issue: https://gis.stackexchange.com/questions/477926/map-moves-every-time-a-marker-is-added-in-ipyleaflet

Potentially related docs: https://ipyleaflet.readthedocs.io/en/latest/api_reference/index.html#ipyleaflet.leaflet.Popup.auto_pan

Potentially related code in `anoph/snp_frq.py`:
```python
        # Add markers.
        for x in df_markers.itertuples():
            marker = ipyleaflet.CircleMarker()
            marker.location = (x.cohort_lat_mean, x.cohort_lon_mean)
            marker.radius = 20
            marker.color = "black"
            marker.weight = 1
            marker.fill_color = "red"
            marker.fill_opacity = x.event_frequency
            popup_html = f"""
                <strong>{variant_label}</strong> <br/>
                Taxon: {x.cohort_taxon} <br/>
                Area: {x.cohort_area} <br/>
                Period: {x.cohort_period} <br/>
                Sample size: {x.cohort_size} <br/>
                Frequency: {x.event_frequency:.0%}
                (95% CI: {x.event_frequency_ci_low:.0%} - {x.event_frequency_ci_upp:.0%})
            """
            marker.popup = ipyleaflet.Popup(
                child=ipywidgets.HTML(popup_html),
            )
            m.add(marker)
```
