### ISSUE TITLE
move to mask="gamb_colu" parameter default?

### ISSUE THREAD

**Issue by cclarkson** [malariagen/malariagen-data-python#27]
Many methods have a `mask ` parameter. Some require this to be given, others will accept `None` which defaults to "gamb_colu_arab".

Firstly this should to be the same for all methods and secondly, if we go with the option for `None`, what should it default to?

**Comment by alimanfoo** [comment]
Currently most Ag3 methods which accept a `site_mask` parameter have default `None` which means that no site mask will be applied. This seems like the best solution to me, as whether or not to apply a site mask generally should be a conscious decision, and which mask to apply depends on the samples being analysed. So closing this, but happy to reopen if further discussion.
