### ISSUE TITLE
Implement interactive haplotype clustering function

### ISSUE THREAD

**Issue by sanjaynagi** [malariagen/malariagen-data-python#284]
Need to write a function in plotly (or bokeh) which clusters haplotypes and produces an interactive dendrogram, in which one can hover over leaves and retrieve metadata about that haplotype. 

proposed function arguments - 

- region
- sample_sets
- sample_query
- analysis (gamb_colu, gambcolu_arab)

optionally - 
- a height to cut tree (total SNP differences in given region) with which we could colour leaves as being part of a haplotype cluster?

any things I've missed?

I assume we will use hamming distance for the hierarchical clustering. What would be the preferred name for this function?

p.s. in general requesting feedback on my issues, pull requests and code where possible :)

**Comment by alimanfoo** [comment]
Thanks Sanj, good write up of the issue. 

One thing to add is that I think we'll want to be able to colour the leaves according to fields in sample metadata. Particularly colouring by country and/or species is important when you want to infer spread of swept haplotype between two countries or species. I.e., we probably want leaf marker colour to be controlled similar to how you'd control marker colour in a standard scatter plot. Possibly also control the leaf marker shape too, although that maybe overcomplicating.
