### ISSUE TITLE
ag3.plot_h1x_gwss() cohort titles not on separate lines but should be

### ISSUE THREAD

**Issue by alimanfoo** [malariagen/malariagen-data-python#291]
Should be a new line between cohort 1 and cohort 2 in plot title.

![image](https://user-images.githubusercontent.com/703554/197062667-a2fe8562-6e0f-434b-9410-a434b8683b50.png)

**Comment by sanjaynagi** [comment]
Just as a reminder, this will also be present in the FST and PBS methods in #294 and #295

**Comment by sanjaynagi** [comment]
Not sure if someone fixed this but FYI its working for me now?
![image](https://user-images.githubusercontent.com/34922269/200348457-cd4ce4b6-ba23-4c00-ac64-425f4e9493cd.png)

**Comment by alimanfoo** [comment]
I can replicate this currently in colab with default bokeh at 2.3. If I upgrade bokeh to 2.4.3 then the problem goes away.
