### ISSUE TITLE
Add haplotypes to Af1 and analytical functions which use haplotypes

### ISSUE THREAD

**Issue by alimanfoo** [malariagen/malariagen-data-python#313]
Haplotypes are now available for the Af1.0 data resource, add support for accessing them via the Af1 API. Public methods are:

* open_haplotypes()
* open_haplotype_sites()
* haplotypes()

Also could then add support for analytical functions which use haplotypes. This could include:

* h12_calibration()
* plot_h12_calibration()
* h12_gwss()
* plot_h12_gwss_track()
* plot_h12_gwss()
* h1x_gwss()
* plot_h1x_gwss_track()
* plot_h1x_gwss()
* plot_haplotype_clustering()
* plot_haplotype_network()

Suggested implementation path is to move these functions into the parent AnophelesDataResource class along with any private functions they require.

**Comment by alimanfoo** [comment]
Hi @leehart, just to mention I created this issue to capture the separate piece of work around refactoring of haplotypes and analytical functions that depend on haplotypes, which could be done as a follow-up to #315.

**Comment by leehart** [comment]
Great, thanks @alimanfoo 👍

**Comment by alimanfoo** [comment]
Resolved via #331.
