### ISSUE TITLE
Add cohorts metadata to Af1 and some analytical functions which require cohorts

### ISSUE THREAD

**Issue by alimanfoo** [malariagen/malariagen-data-python#315]
Cohort metadata are available for the Af1.0 data resource, propose to include those cohort metadata in the sample metadata from the Af1 API, similar to the Ag3 API.

Also propose to add support in Af1 for several analytical functions which require SNP data and cohort metadata. This could include:

* snp_allele_frequencies()
* aa_allele_frequencies()
* plot_frequencies_heatmap()
* snp_allele_frequencies_advanced()
* aa_allele_frequencies_advanced()
* plot_frequencies_time_series()
* plot_frequencies_map_markers()
* plot_frequencies_interactive_map()
* snp_allele_counts()
* plot_pca_coords()
* plot_pca_coords_3d()
* cohort_diversity_stats()
* diversity_stats()
* plot_diversity_stats()
* plot_samples_interactive_map()
* count_samples()
* fst_gwss()
* plot_fst_gwss_track()
* plot_fst_gwss()

Suggested implementation path is to move these functions into the parent AnophelesDataResource class along with any private functions they require.

**Comment by alimanfoo** [comment]
cc @jorels1

**Comment by alimanfoo** [comment]
Forgot to include the Fst functions that @sanjaynagi added recently, have added to the issue description.

**Comment by leehart** [comment]
Thanks @alimanfoo . I'll make sure to include those.
As discussed, I will aim to add support for the Af1.0 haplotype data under a separate issue later, assuming those functions aren't intertwined.

**Comment by alimanfoo** [comment]
Btw just looking again at the list of analytical functions included here, there are quite a few. I'm guessing that moving those functions up into the parent class shouldn't be too hard, but refactoring the tests might be a bit more involved. And there's a question of if we want to add any tests for Af1 and if so how thoroughly we test. 

Two thoughts:

* If resolving this issue all in one PR starts to get hairy, then no objection to breaking it up a bit into separate PRs.
* Regarding tests for Af1, FWIW I'd be happy with light testing, basically just to check that the plumbing is working. (The analytical code has already been pretty thoroughly tested via tests for Ag3 and via usage in the training course notebooks.)

**Comment by leehart** [comment]
My previous strategy was to move tests that were shallow/simple enough to parameterise to the parent `test_anopheles.py`, and keep the others that were more involved (or too "hairy" to generalise) in the child contexts, i.e. `test_af1.py` and `test_ag3.py`. In that way I don't think there was any decrease in test coverage, although that might cause code duplication when we get a complex test in both Ag and Af.

But it sounds like these analytical functions might be a different kettle of fish, so I'll see what I can do, and I'll follow your advice.

**Comment by alimanfoo** [comment]
Thanks @leehart, your testing approach SGTM. What you have in `test_anopheles.py` tests the plumbing works for both Ag3 and Af1, so that seems good. Then any more complex tests can be for Ag3 only at least for now.

**Comment by leehart** [comment]
By the way, I also have some tests failing for Pf7, concerning the `pf7_staging` bucket. I wonder if resources have been moved/changed there too. It seems odd/wrong to be relying on a "staging" bucket for API tests.

**Comment by leehart** [comment]
There are other failures due to the new Af GFF3 not containing the expected `Name` attribute.

**Comment by leehart** [comment]
I would have thought that these test failures should have been fixed by the merged PR #307, so I'm not sure why I'm still hitting these, especially because the CI should have caught it too.

Somehow, I don't think I have the latest code. I should have v7.1.3 rather than v7.0.2, despite having pulled the latest master... Investigating.

**Comment by leehart** [comment]
Closed by merged PR #318
