### ISSUE TITLE
Documentation for Af1 API

### ISSUE THREAD

**Issue by leehart** [malariagen/malariagen-data-python#326]
It would be good to have documentation of the Af1 class, preferably at https://malariagen.github.io/vector-data/af1/api.html

Akin to:

* [Ag3 API docs](https://malariagen.github.io/vector-data/ag3/api.html)
* [Amin1 API docs](https://malariagen.github.io/vector-data/amin1/api.html)
* [Pf7 API docs](https://malariagen.github.io/parasite-data/pf7/api.html)
* [Pv4 API docs](https://malariagen.github.io/parasite-data/pv4/api.html)

**Comment by alimanfoo** [comment]
https://malariagen.github.io/malariagen-data-python/latest/Af1.html
