### ISSUE TITLE
Implement XPEHH GWSS methods for Anopheles

### ISSUE THREAD

**Issue by alimanfoo** [malariagen/malariagen-data-python#333]
Propose to add functions to run and plot XPEHH GWSS.

xref https://nbviewer.org/github/alimanfoo/shiny-train/blob/master/notebooks/gwss/xpehh_scans.ipynb

**Comment by jonbrenas** [comment]
I was going to start writing some code but I think there might be some questions that I need to ask first:
1) Do we return an array for several metrics (max, pc90, ...) or do we give the user the option of choosing the one(s) they prefer?
2) Do we always clip/center or do we give the user a choice?

**Comment by alimanfoo** [comment]
Hi @jonbrenas, regarding these questions, I'd suggest to take a look at the IHS implementation by @sanjaynagi, and follow conventions there as much as seems reasonable.

**Comment by alimanfoo** [comment]
Closed via #394
