### ISSUE TITLE
Add site filters to Af1 IGV functions

### ISSUE THREAD

**Issue by alimanfoo** [malariagen/malariagen-data-python#335]
Site filters in VCF format now available, add in a track to IGV.

**Comment by leehart** [comment]
Just to note here that we currently have a placeholder `_view_alignments_add_site_filters_tracks()` in `af1.py`.

It looks like there are only a few lines of code to copy, and a path to adapt, from the existing  `_view_alignments_add_site_filters_tracks` in `ag3.py`.

I suppose we might be able to abstract their commonality into `anopheles.py`, but I'm not sure about that yet.
