### ISSUE TITLE
Show more information in plot_samples_interactive_map() hover text

### ISSUE THREAD

**Issue by alimanfoo** [malariagen/malariagen-data-python#342]
Currently we show some information in hover text...

![image](https://user-images.githubusercontent.com/703554/221822121-e192b73d-8cee-48e6-9b7e-ad9ba9d3f611.png)

...but would be nice to show a bit more info, including years, sample sets and contributors.

**Comment by leehart** [comment]
It looks like we should be able to add that info to the `pivot_table()` in `plot_samples_interactive_map()` in `anopheles.py`.
That function already grabs all of `sample_metadata(sample_sets=sample_sets, sample_query=sample_query)`, which should contain `contributor` and `year`.
