### ISSUE TITLE
pomegranate on Colab

### ISSUE THREAD

**Issue by leehart** [malariagen/malariagen-data-python#388]
Reported by @korlevic

On Google Colab with Python 3.9.16, installing the default version of pomegranate via `!pip install` (for functions such as `plot_roh`) currently results in pomegranate v1.0.0, which no longer has `HiddenMarkovModel`, so the current `plot_roh` function fails, due to "ImportError: cannot import name 'HiddenMarkovModel' from 'pomegranate'".

Whereas installing v0.14.8 of pomegranate on Colab, via `!pip install pomegranate==0.14.8`, currently fails after `import pomegranate` due to:
> RuntimeError: module compiled against API version 0x10 but this version of numpy is 0xf . Check the section C-API incompatibility at the Troubleshooting ImportError section at https://numpy.org/devdocs/user/troubleshooting-importerror.html#c-api-incompatibility for indications on how to solve this problem .

Followed by:
> ImportError: numpy.core.multiarray failed to import

**Comment by alimanfoo** [comment]
This is the underlying problem when trying to install pomegranage v0.14.8 - https://github.com/pypa/pip/issues/9542

A workaround is to disable build isolation, which forces pomegranate to be compiled within the some Python environment that it's going to be used in. In this case, all build dependencies are already installed on colab, so this should be all that's needed:

```
!pip install --no-build-isolation pomegranate==0.14.8
```

**Comment by alimanfoo** [comment]
Suggest we close this issue as there is a workaround. There is a larger piece of work though to upgrade to pomegranate 1.0. That is probably something for upstream libraries, either scikit-allel or sgkit.
