### ISSUE TITLE
Consider using relative path in `Ag3.aim_calls()`

### ISSUE THREAD

**Issue by ahernank** [malariagen/malariagen-data-python#392]
The path is hard-coded to use the release bucket in `_aim_calls_dataset()`. We could use `self._base_path` instead, which will allow to test/use the function with other data (useful during staging). This will also be consistent with `aim_variants()`.

**Comment by alimanfoo** [comment]
Thanks @ahernank, good call, don't know how that slipped in there. 

Also could use the `self._aim_analysis` property to inject the analysis version, rather than that being hardcoded too.

PR welcome.

**Comment by alimanfoo** [comment]
Addressing this via #405.
