### ISSUE TITLE
Anopheles refactor CNV data access functions

### ISSUE THREAD

**Issue by alimanfoo** [malariagen/malariagen-data-python#404]
As part of work towards #366 we'd like to refactor the functions for accessing CNV data out into a separate module and class, following a similar approach to that taken for SNP data and haplotype data.

We'd also like to make these functions available as part of the Af1 API, as the CNV data will be available soon.

Raising this issue to plan out the work involved.

**Comment by alimanfoo** [comment]
Here is a proposed implementation plan:

## Part 1 - setup

1. Create a new module `malariagen_data.anoph.cnv_data`. Inside that module, declare a new class `AnophelesCnvData`. This class will inherit from parents `AnophelesSampleMetadata`, `AnophelesGenomeFeaturesData`, `AnophelesGenomeSequenceData`. Constructor for this class probably doesn't need to take any specific arguments, should just be able to take `**kwargs` and pass through to `super().__init__(**kwargs)`.
2. Change the definition of the `AnophelesDataResource` class to add `AnophelesCnvData` as a parent class. Make sure this occurs as the first parent in the list of parent classes.

At this point, you should be ready to start moving CNV data access functions from the `Ag3` class up to the `AnophelesCnvData` class. As you're doing so, the existing tests in the `test_ag3` module should still continue to run and pass. The `plot_cnv` notebook should also continue to work.

## Part 2 - code refactoring

Here's a suggested order for moving code from `Ag3` to `AnophelesCnvData`:

3. Move the declaration of the cache variables in the constructor function `_cache_cnv_hmm`, `_cache_cnv_coverage_calls`, `_cache_cnv_discordant_read_calls`.
4. Move the methods `open_cnv_hmm`, `_cnv_hmm_dataset`, `cnv_hmm`.
5. Move the methods `open_cnv_coverage_calls`, `_cnv_coverage_calls_dataset`, `cnv_coverage_calls`.
6. Move the methods `open_cnv_discordant_read_calls`, `_cnv_discordant_read_calls_dataset`, `cnv_discordant_read_calls`.
7. Move the plotting methods `plot_cnv_hmm_coverage_track`, `plot_cnv_hmm_coverage`, `plot_cnv_hmm_heatmap_track`, `plot_cnv_hmm_heatmap`.

Note that I suggest leaving the methods relating to CNV frequencies alone for now (`gene_cnv_frequencies` etc.) and dealing with those in a later PR.

## Part 3 - type hints and documentation

Now that the functions are moved, we can add type hints (annotations) and use the `@doc` decorator to allow type checking and improve maintainability.

8. Add a `malariagen_data.anoph.cnv_params` module. Within this, declare any parameter types that are specific to CNV data access functions. (I think there is just one - `max_coverage_variance` - but worth sticking to the pattern of having separate params modules, similar to `malariagen_data.anoph.hap_params`.)
9. Add type hints to all parameters in all public methods in the `AnophelesCnvData` class.
10. Replace hand-written docstrings with use of the `@doc` decorator on all public methods in the `AnophelesCnvData` class.

At this point, all code refactoring work will be complete. All `Ag3` tests should still pass, i.e., no loss or change of functionality in the `Ag3` API. Also, CNV data access functions will now be available on the `Af1` class, because this inherits from `AnophelesDataResource` which inherits from `AnophelesCnvData`.

## Part 4 - test refactoring

As a final step, we could refactor the tests to use simulated data (making them run much faster) and also test both Ag3 and Af1 APIs. This would involve:

11. Add functionality to the `tests/anoph/conftest.py` module to roughly simulate CNV data.
12. Refactor all test code in the `tests/test_ag3.py` module relating to CNV data access functions into a new module at `tests/anoph/test_cnv_data.py` and rework it to use simulated data instead of data from GCS.

---

Lots of work here, but can be taken step by step. Good news is the existing test suite should help us to verify any refactoring work has not broken anything for the Ag3 API, and so we'll be confident refactoring is sound before we undertake any changes to the test suite.

Also, part 4 could be undertaken as a separate piece of work, if that would make life easier. I.e., have one PR that deals with parts 1-3 above, then a second PR dealing with part 4.

**Comment by alimanfoo** [comment]
Hi @leehart, FYI, just thinking ahead here and making a few notes on a possible way forward for the CNV data access functions.

**Comment by leehart** [comment]
Hi @alimanfoo . Re: step 9. Only public methods? Is this limitation just to save time, because I see type hints already being used in some methods with underscore prefixes, e.g. `_site_filters_for_region`. I'm conscious that Python doesn't have true privacy, just this underscore convention for indicating private methods.

**Comment by leehart** [comment]
Completed.
