### ISSUE TITLE
Label genes

### ISSUE THREAD

**Issue by alimanfoo** [malariagen/malariagen-data-python#407]
It would be useful to be able to label some genes of interest in a genes plot. 

The bokeh [LabelSet](https://docs.bokeh.org/en/latest/docs/reference/models/annotations.html#bokeh.models.LabelSet) feature looks potentially useful here, see also [bokeh labels docs](https://docs.bokeh.org/en/latest/docs/user_guide/basic/annotations.html#labels).

**Comment by leehart** [comment]
While trying this out, I encountered an amusing problem, which arises if I put a label on every gene, e.g. using its gene ID... When zoomed out the gene tracks become long smears of incoherent overlapping text, where the labels go beyond the limits of their gene and overlap each other. So I need to devise some way to avoid this... 🤔 

<img width="740" alt="Screenshot 2024-10-24 at 18 27 07" src="https://github.com/user-attachments/assets/3a45674b-5127-4969-b1f6-b00ed335ac41">
<img width="743" alt="Screenshot 2024-10-24 at 18 26 46" src="https://github.com/user-attachments/assets/31178a63-55aa-4ca1-a683-3ceb8c0a5ae2">

**Comment by alimanfoo** [comment]
Maybe something like this...?

![image](https://github.com/user-attachments/assets/326ec229-f838-4547-8cc5-47552353fa44)

From [here](https://pubmed.ncbi.nlm.nih.gov/29186111/).
