### ISSUE TITLE
Cannot use variables in sample query

### ISSUE THREAD

**Issue by amakunin** [malariagen/malariagen-data-python#410]
it seems that `sample_query` in `snp_calls` does not work well with variables referencing, i.e
```
sample_list = some_sample_selection_result
ag3.snp_calls(region='3L', site_mask='gamb_colu', sample_query='sample_id in @sample_list')
```
raises a key error stating sample_list  is not recognised

I suspect that it is due to differences in query syntax between pandas and xarray

**Comment by EricRLucas** [comment]
Just ran into this problem too and offering a cludgy hack fix that works if the list is small enough. If sample_list is a python list, you can do:

ag3.snp_calls(region='3L', site_mask='gamb_colu', sample_query=f'sample_id in {sample_list}')

The interpreter then just expands the sample_list object into the query string and it seems to work. It fails if the list is too long though, as the expansion gets truncated. 

Hopefully that's useful to someone running into the same issue.

**Comment by leehart** [comment]
We have some caching in places and dict isn't hashable, so I'm looking at workarounds.

**Comment by leehart** [comment]
In some cases at least, it looks like we can refactor so that `@lru_cache` is still applied to parts that matter without encompassing the new mutable arg.
