### ISSUE TITLE
haplotype networks does not work on bespin

### ISSUE THREAD

**Issue by jorels1** [malariagen/malariagen-data-python#415]
``It appears that the plot_haplotype_network function for both Af1 and Ag3 does not work on bespin.

I tried it on collab and everything works fine. May be something to do with some settings on bespin.

I built a custom notebook on bespin: (https://datalab-bespin.malariagen.net/user/jorels1/lab/workspaces/auto-v/tree/gitRepo/vobs-funestus/work/329_haplotype_networks/compute_haplotype_networks.ipynb,  branch: 329_haplotype_networks). And here you can see that my code works right until Dash plotting and then I get an errror that begins like this:
`Dash is running on http://x86_64-conda-linux-gnu:8049/

Name or service not known
---------------------------------------------------------------------------
gaierror                                  Traceback (most recent call last)
File /home/conda/global/6b322fe463cada321b02dc882e2421921f59cbf9b785cecda69fdb6bfc6c5abc-20230520-114958-558686-26-binder-4.5.0/lib/python3.10/site-packages/urllib3/connection.py:174, in HTTPConnection._new_conn(self)
    173 try:
--> 174     conn = connection.create_connection(
    175         (self._dns_host, self.port), self.timeout, **extra_kw
    176     )
    178 except SocketTimeout:

File /home/conda/global/6b322fe463cada321b02dc882e2421921f59cbf9b785cecda69fdb6bfc6c5abc-20230520-114958-558686-26-binder-4.5.0/lib/python3.10/site-packages/urllib3/util/connection.py:72, in create_connection(address, timeout, source_address, socket_options)
     68     return six.raise_from(
     69         LocationParseError(u"'%s', label empty or too long" % host), None
     70     )
---> 72 for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
     73     af, socktype, proto, canonname, sa = res

File /home/conda/global/6b322fe463cada321b02dc882e2421921f59cbf9b785cecda69fdb6bfc6c5abc-20230520-114958-558686-26-binder-4.5.0/lib/python3.10/socket.py:955, in getaddrinfo(host, port, family, type, proto, flags)
    954 addrlist = []
--> 955 for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
    956     af, socktype, proto, canonname, sa = res

gaierror: [Errno -2] Name or service not known`

This same error occurs when I load af1 API and run the code `af1.plot_haplotype_network(region='2RL:8,680,464-8,700,407', max_dist=2,)`.

Running plot_haplotype_network on ag3 data gives a Permission error instead:
---------------------------------------------------------------------------
PermissionError                           Traceback (most recent call last)
File /home/conda/global/envs/global-binder-4.5.0/lib/python3.10/site-packages/distributed/scheduler.py:4282, in update_graph()
   4280     from distributed.protocol import deserialize
-> 4282     graph = deserialize(graph_header, graph_frames).data
   4283 except Exception as e:

File /home/conda/global/envs/global-binder-4.5.0/lib/python3.10/site-packages/distributed/protocol/serialize.py:432, in deserialize()
    431 dumps, loads, wants_context = families[name]
--> 432 return loads(header, frames)

File /home/conda/global/envs/global-binder-4.5.0/lib/python3.10/site-packages/distributed/protocol/serialize.py:98, in pickle_loads()
     93 buffers = [
     94     memoryview(bytearray(mv) if w else bytes(mv)) if w == mv.readonly else mv
     95     for w, mv in zip(writeable, map(ensure_memoryview, buffers))
     96 ]
---> 98 return pickle.loads(x, buffers=buffers)

File /home/conda/global/envs/global-binder-4.5.0/lib/python3.10/site-packages/distributed/protocol/pickle.py:94, in loads()
     93 if buffers:
---> 94     return pickle.loads(x, buffers=buffers)
     95 else:

File /home/conda/global/envs/global-binder-4.5.0/lib/python3.10/site-packages/fsspec/spec.py:28, in make_instance()
     27 def make_instance(cls, args, kwargs):
---> 28     return cls(*args, **kwargs)

**Comment by jorels1** [comment]
Hi @alimanfoo, @cclarkson, please could you look into this at your earliest convenience. I am still unable to run haplotype networks on bespin or datalab. The story is the same whether using ag3 or af1 samples or API.

**Comment by leehart** [comment]
It's difficult to diagnose these connection issues, which might be specific to the machine rather than the `plot_haplotype_network()` function of this Python package.

I suggest we run some simple tests to check basic behaviour of this function, see if we can reproduce any errors with a minimal test case, and perhaps add an automated test.

Have we had any other recent reports of this function not working in this way, or generally working on MalariaGEN DataLab?

**Comment by leehart** [comment]
- [x] Confirmed working OK on Colab https://colab.research.google.com/drive/119a4BhY8f8ghO8T-O2CotX_aJqnHV-vw?usp=sharing
- [ ] Checking on DataLab Bespin...

**Comment by leehart** [comment]
Confirmed that this is still a problem on DataLab Bespin, e.g. with recent mgenv:
<img width="1012" alt="Screenshot 2024-09-20 at 12 51 01" src="https://github.com/user-attachments/assets/cff64f86-3f46-469d-9df4-e2c411c99f97">

**Comment by leehart** [comment]
Unfortunately it has been decided that we won't plan to fix this, due to complications around using Dash in the MalariaGEN DataLab environment, which I don't yet understand.

Unhelpful links:
- [plot_haplotype_network()](https://github.com/malariagen/malariagen-data-python/blob/55432a5c8b5d5d680fd11fb1038b5df3551ac3f9/malariagen_data/anopheles.py#L2747)
- [Dash in Jupyter environments](https://dash.plotly.com/dash-in-jupyter)
