### ISSUE TITLE
plot_samples_interative_map() - `center` and `zoom` parameters

### ISSUE THREAD

**Issue by cclarkson** [malariagen/malariagen-data-python#421]
The `center` and `zoom` parameters for plot_samples_interative_map() only accept integers. It also appears that the centre function may not actually be working at all (even with integers).

**Comment by leehart** [comment]
The `center` bug will be handled under issue #208 for which there is now a PR #624 for a potential solution.

The data type for the `center` param appears to be set in `anoph/map_params.py`, i.e.
```python
center: TypeAlias = Annotated[
    Tuple[int, int],
    "Location to center the map.",
]
```
I'll try to make a separate PR to remedy that soon.
