### ISSUE TITLE
pytest error

### ISSUE THREAD

**Issue by jonbrenas** [malariagen/malariagen-data-python#438]
I was running `poetry run pytest -v` and there are 4 errors (but they are actually 2 errors twice):

- ValueError: No samples found for query "cohort_admin2_year == 'GH-NP_Tolon-Kumbungu_fune_2017'"
- AssertionError: assert ['AO-LUA_colu...mb_2014', ...] == ['AO-LUA_colu...mb_2014', ...] [...] At index 24 diff: 'GM-L_gcx2_2006' != 'GM-L_gcx2_2012'

I know there is ongoing work on funestus from Ghana and that the metadata for AG1000G-GM-B was updated by @ahernank so I think some functions are looking at old cohort definitions. Are these known errors? Have I forgotten a step during setup that causes them?

**Comment by ahernank** [comment]
Yes, we did update the tests in  #417 to solve the tests related to AG1000G-GM-B; so I would hope this would be addressed now. 

Wondering if there is come local cache that could be affecting things?

**Comment by ahernank** [comment]
Lee has also addressed the first issue related to the cohort query in #424.

**Comment by jonbrenas** [comment]
Thanks @ahernank. I'll try to find why the cache is pulling my leg and how to clear it.
