### ISSUE TITLE
KeyError: 'Stamen'

### ISSUE THREAD

**Issue by alimanfoo** [malariagen/malariagen-data-python#443]
As of [release 2023.10.1](https://github.com/geopandas/xyzservices/releases/tag/2023.10.1) xyzservices has removed stamen tiles.

This causes `KeyError: 'Stamen'` when trying to import malariagen_data.

Temporary workaround:

```
pip install malariagen_data "xyzservices < 2023.10.1"
```

**Comment by alimanfoo** [comment]
Hi @leehart, any chance you could find a fix for this and make a micro release?

**Comment by leehart** [comment]
> Hi @leehart, any chance you could find a fix for this and make a micro release?

Hi @alimanfoo . Sure, I'll do it first thing tomorrow.

**Comment by alimanfoo** [comment]
Awesome, thanks @leehart. Sorry forgot you were away today.

**Comment by leehart** [comment]
I had assumed from GeoPandas' statement `Use Stamen styles of Stadia provider instead` that these tiles would be available via Stadia instead, e.g.
```python
    "terrain": ipyleaflet.basemaps.Stadia.StamenTerrain,
    "watercolor": ipyleaflet.basemaps.Stadia.StamenWatercolor,
```
but judging from Stamen's FAQs and this test, it looks like we might have to drop our support for `watercolor` and `terrain` maps from our `map_params.py`, sadly
<img width="921" alt="Screenshot 2023-11-09 at 11 58 14" src="https://github.com/malariagen/malariagen-data-python/assets/4256466/a82e43a1-5945-4ce7-b8ee-efe9396c270a">

**Comment by leehart** [comment]
From https://stadiamaps.com/stamen/
> I thought Stamen Map Tiles were free?
> For many years, Stamen offered a completely free map tile service. Unfortunately, mapping services are expensive to maintain, and it wasn’t possible to continue supporting an entirely free service. We partnered with Stamen to continue offering these iconic styles as part of the Stadia Maps’ platform.

**Comment by leehart** [comment]
A new patch release has now been made (v7.14.1), but we probably want to guard against this fragility, somehow.
