### ISSUE TITLE
Say "cohort" instead of "population"

### ISSUE THREAD

**Issue by alimanfoo** [malariagen/malariagen-data-python#46]
For functions like snp_allele_frequencies, the "populations" parameter specifies groups of mosquitoes. However, "population" isn't really the right term. Also, sgkit is using "cohort" to mean a group of samples. We should probably consistify now, easier than later.

**Comment by cclarkson** [comment]
Hmm, but cohort often has a temporal connotation that might confuse folk (I know we used population inappropriately too!). Happy to consistify though :)

**Comment by alimanfoo** [comment]
I know, it's not my favourite either, but the sgkit folks have gone for it, it's baked in to their API in quite a few places now.
