### ISSUE TITLE
`af1.add_extra_metadata()` FileNotFoundError

### ISSUE THREAD

**Issue by sanjaynagi** [malariagen/malariagen-data-python#505]
Greetings all. 

We are getting a file not found error when trying to add extra metadata to Af1. This just started happening yesterday. 

![image](https://github.com/malariagen/malariagen-data-python/assets/34922269/cff426c2-9f97-4787-a334-7c778366d82c)

**Comment by ahernank** [comment]
Thanks @sanjaynagi! Apologies, I was moving some files around yesterday but this should be fixed now.

**Comment by sanjaynagi** [comment]
No worries @ahernank ! Thanks, thats fixed it :)

Closing issue.
