### ISSUE TITLE
A function or method to know what is under embargo and what is free to use

### ISSUE THREAD

**Issue by sanjaynagi** [malariagen/malariagen-data-python#508]
Since all data are now available in ag3 without the use of (pre=True), I find myself performing exploratory analyses only to not know what data I can and can't use. 

I feel that this is a common predicament, multiple times I have spoken to trainees, or they have presented data, which uses sample sets that are either not 'public' or not 'theirs to use'. Generally, they are not aware of what they can and cannot use. 

Admittedly it may not be that clear cut, but it would be great to be able to return a list of sample sets which are either public or 2 years after production (if that is the embargo rule).

**Comment by alimanfoo** [comment]
Thanks @sanjaynagi, yes this is definitely something I'd like to add.

We would need to first add in the underlying data somewhere, i.e., for each sample set, are there terms of use, and if so, when do the terms of use expire. We could then pull this through into the dataframes returned by methods such as `sample_sets()` and `sample_metadata()`.

I was thinking we could begin by adding the following columns into the sample set manifest for each release:

* `terms_of_use` - bool - True if terms of use apply, or False if not
* `terms_of_use_expiry_date` - date - Date on which terms of use expire.
* `terms_of_use_url` - string - URL where terms of use are published.

We could then add a dynamically calculated column in the API called `unrestricted_use` which would be True if `terms_of_use` is False or if the `terms_of_use_expiry_date` has passed.

Then users would be able to make sample queries like `country == 'Burkina Faso' and unrestricted_use`.

**Comment by leehart** [comment]
The terms-of-use info and `unrestricted_use` field have now been added.
