### ISSUE TITLE
Diplotype clustering fails on sample sets without CNV calls 

### ISSUE THREAD

**Issue by sanjaynagi** [malariagen/malariagen-data-python#555]
![image](https://github.com/malariagen/malariagen-data-python/assets/34922269/10ae5217-3cbf-4979-8134-c61c11ca33cd)

There are no CNV calls for this sample set so it fails. Earlier versions of the diplotype clustering function had a try/except statement to get around this, could implement something like that.

**Comment by sanjaynagi** [comment]
temporary workaround 

`  
sample_sets=[s for s in ag3.sample_sets()['sample_set'].to_list() if s != 'barron-2019']
`

**Comment by alimanfoo** [comment]
Seems fine to handle this error internally, but how do we communicate to the user that the data are missing? Need to make sure it doesn't look like these samples have normal copy number.

**Comment by leehart** [comment]
Related issue https://github.com/malariagen/malariagen-data-python/issues/363

**Comment by leehart** [comment]
Would it be sufficient to simply skip sample sets that don't have CNV HMM data in the API?

Essentially:
```python
                    y = self._cnv_hmm_dataset(
                        contig=r.contig,
                        sample_set=s,
                        inline_array=inline_array,
                        chunks=chunks,
                    )

                    # If no CNV HMM dataset was found then skip
                    if y is None:
                        continue

                    ly.append(y)
```

For example, I can submit a PR that would allow:
```python
ag3.plot_diplotype_clustering_advanced(
  region='2L:28,535,000-28,552,000',
  cnv_region='2L:28,535,000-28,552,000',
  sample_query='taxon == "gambiae" and year > 2019',
  site_mask='gamb_colu_arab',
  color='taxon',
  snp_transcript='AGAP006227-RA',
)
```
![newplot](https://github.com/malariagen/malariagen-data-python/assets/4256466/b297c3f2-16e8-4bb0-afcd-6626a8491e6f)

**Comment by leehart** [comment]
We now skip sample sets that don't have CNV HMM data but still raise `ValueError` when no CNV HMM data are found at all.
