### ISSUE TITLE
Advanced diplotype clustering orders genes in the CNV section by label rather than by genomic position

### ISSUE THREAD

**Issue by alimanfoo** [malariagen/malariagen-data-python#558]
If the `cnv_region` contains multiple genes, the CNV heatmap rows will be ordered by the gene label rather than their genomic position. This can make it a bit confusing to try to understand the structure of the CNVs. Would be better to order by genomic position.

**Comment by alimanfoo** [comment]
Here's an example:

```python
af1.plot_diplotype_clustering_advanced(
    region='X:8,438,477-8,460,887',
    snp_transcript='LOC125764232_t1',
    cnv_region='X:8,418,477-8,480,887',
    sample_sets=['1232-VO-KE-OCHOMO-VMF00044', '1231-VO-MULTI-WONDJI-VMF00043', '1236-VO-TZ-OKUMU-VMF00090'],
    sample_query="country in ['Kenya', 'Uganda', 'Tanzania'] and taxon == 'funestus'",
)
```
![image](https://github.com/malariagen/malariagen-data-python/assets/703554/11f30bec-f23d-457f-84cc-31eb5024074b)

**Comment by sanjaynagi** [comment]
interesting, didnt notice this!

**Comment by sanjaynagi** [comment]
Just had a look at your example in the Af1 GFF, they are already in the order of genomic position, although LOC125764275 (middle gene) is on reverse strand. 

![image](https://github.com/malariagen/malariagen-data-python/assets/34922269/cce93b62-af03-4e24-bee8-5ffe666eb0ec)

So for some reason CNVs at LOC125764275 are not getting called.

**Comment by alimanfoo** [comment]
> Just had a look at your example in the Af1 GFF, they are already in the order of genomic position, although LOC125764275 (middle gene) is on reverse strand.

No I don't think so, here are the three genes in the region I wanted to show CNV data for...

![image](https://github.com/malariagen/malariagen-data-python/assets/703554/ff615e43-7fc3-44a3-a1cf-8336c11c9476)

The middle gene should be LOC125764232 but it's not.

Actually, maybe the problem is that the GFF isn't sorted...

**Comment by alimanfoo** [comment]
Suggested fix is to sort the GFF when it is loaded within the genome_features() function.

**Comment by sanjaynagi** [comment]
Did this ever get resolved? @leehart @alimanfoo

**Comment by sanjaynagi** [comment]
i can do it
