### ISSUE TITLE
Display normal copy number (2) differently from missing CNV call (NaN) in advanced diplotype clustering

### ISSUE THREAD

**Issue by alimanfoo** [malariagen/malariagen-data-python#559]
Currently missing CNV HMM data due to high coverage variance is rendered in white in the CNV heatmap. Normal copy number of 2 is also rendered as white. This can be confusing and allow mistaken interpretation of the data.

E.g., here is a plot with the default value for `cnv_max_coverage_variance`:

![image](https://github.com/malariagen/malariagen-data-python/assets/703554/dbeee265-ff08-49d1-9cb8-c53e96926e05)

Here's the same plot but with `cnv_max_coverage_variance` set to None, showing that lots of samples which appeared white previously were due to high coverage variance:

![image](https://github.com/malariagen/malariagen-data-python/assets/703554/8971d8a6-9779-406e-938f-9afe61a039da)

**Comment by alimanfoo** [comment]
Suggest to use the same grey that the `plot_cnv_hmm_heatmap()` function uses for missing HMM state.

**Comment by sanjaynagi** [comment]
In my plots there is a difference, although admittedly its very faint.

NaNs are white, whereas copy number of 2 is a VERY light grey. Perhaps we can increase this contrast and/or switch up the colours as you say. 

I think NaNs are transparent - a solution online is to change the background colour of the plot, may give that a go - its not obvious how you assign a colour to NaN in plotlys colorscale 


![image](https://github.com/malariagen/malariagen-data-python/assets/34922269/4bcfb13a-6595-41c6-a51e-27d679c0b0e0)

**Comment by sanjaynagi** [comment]
In bokeh CNV plots, NaN recoded to -1
