### ISSUE TITLE
Study URL in sample_metadata() is hard-coded rather than sourced from manifest.tsv 

### ISSUE THREAD

**Issue by leehart** [malariagen/malariagen-data-python#562]
This means, for example, that literature sample sets such as `fontaine-2015-rebuild` show the wrong study URL (i.e. not the one from the release `manifest.tsv`) when running `sample_metadata()`.

`anoph/sample_metadata.py`
```python
            study = self.lookup_study(sample_set=sample_set)
            df["study_id"] = study
            df[
                "study_url"
            ] = f"https://www.malariagen.net/network/where-we-work/{study}"
```

I plan to fix this via PR #560 as terms-of-use info are added.

**Comment by alimanfoo** [comment]
Resolved via #560.
