### ISSUE TITLE
FST plotting function error

### ISSUE THREAD

**Issue by KellyLBennett** [malariagen/malariagen-data-python#567]
The FST function should give the standard error or Z score when called on the diagonal. However the first row is swapped with the first column. Please see the figures below. The first is the plot with just FST and the second is a plot which should show Z score on the diagonal. 

<img width="480" alt="Screenshot 2024-07-10 at 16 22 50" src="https://github.com/malariagen/malariagen-data-python/assets/79805293/c7b1b252-ab4b-4088-ac41-40a89c49ce52">

<img width="499" alt="Screenshot 2024-07-10 at 16 24 29" src="https://github.com/malariagen/malariagen-data-python/assets/79805293/8c7ff67b-95c4-4ae0-84c7-80eaf2ae1de1">

**Comment by alimanfoo** [comment]
Hi @KellyLBennett, just having a look at this now, would you be able to post the function call you made to generate the plots above so I can try to replicate?

**Comment by KellyLBennett** [comment]
Hi alimanfoo I believe this was when running the following
```
fst_df= ag3.pairwise_average_fst(region="3L:15,000,000-41,000,000", cohorts=wild_cohorts,min_cohort_size=10,site_mask="arab")
ag3.plot_pairwise_average_fst(fst_df,annotation ="Z score")
```

**Comment by alimanfoo** [comment]
Thanks @KellyLBennett. Can you provide the value of the `wild_cohorts` parameter?

**Comment by KellyLBennett** [comment]
Sorry yes, here it is. 

```
wild_cohorts = {
                    "Mwea_2007" : f"taxon == 'arabiensis' and location == 'Mwea' and year == 2007 and insecticide == 'Untested' and partner_sample_id not in {misplaced_samples_list}",
                    "Mwea_2014" : f"taxon == 'arabiensis' and location == 'Mwea' and year == 2014 and insecticide == 'Untested' and partner_sample_id not in {misplaced_samples_list}",
                    "Teso_2013" : f"taxon == 'arabiensis' and location == 'Teso' and insecticide == 'Untested' and partner_sample_id not in {misplaced_samples_list}",
                    "Turkana_2006" : f"taxon == 'arabiensis' and location == 'Turkana' and insecticide == 'Untested' and partner_sample_id not in {misplaced_samples_list}",
                    "Kilifi_2012" : "taxon == 'arabiensis' and location == 'Kilifi' and year == 2012"}
```

**Comment by alimanfoo** [comment]
Thanks @KellyLBennett, I can replicate with this slightly simplified example:

![image](https://github.com/user-attachments/assets/99f0a327-0e17-4585-ba21-c032c3bf6ade)
