### ISSUE TITLE
Switch off site filters

### ISSUE THREAD

**Issue by leehart** [malariagen/malariagen-data-python#631]
User expects to be able to switch off the site filters, e.g. via
```python
af1 = malariagen_data.Af1(site_filters_analysis=None)
```
...but the `site_filters_analysis` still appears to be the default, i.e. `DEFAULT_SITE_FILTERS_ANALYSIS`

If we want to allow "no site filters" as an option, perhaps this code from `anoph/snp_data.py` needs to change:
```python
    @property
    def _site_filters_analysis(self) -> Optional[str]:
        if self._site_filters_analysis_override:
            return self._site_filters_analysis_override
        else:
            # N.B., this will return None if the key is not present in the
            # config.
            return self.config.get("DEFAULT_SITE_FILTERS_ANALYSIS")
```

**Comment by alimanfoo** [comment]
Hi @leehart, it's possible switch off site filters when making calls to specific functions, by passing `site_mask=None`.

**Comment by leehart** [comment]
Using `site_mask=None` was initially suggested to the user, specifically for the `snp_allele_frequencies` function in the context of Af1, but they reported that it didn't work. Will investigate further.

**Comment by alimanfoo** [comment]
> Using `site_mask=None` was initially suggested to the user, specifically for the `snp_allele_frequencies` function in the context of Af1, but they reported that it didn't work. Will investigate further.

Thanks. The default value for `site_mask` in the `snp_allele_frequencies()` function is `None`, so all SNPs should get output by default.

**Comment by leehart** [comment]
I suspect some of the confusion might arise from the `__repr__` (and `_repr_html_`) reporting:
```python
f"Site filters analysis   : {self._site_filters_analysis}\n"
```
which might convince users that these filters are always in effect, although in this case they were convinced by the output of the function.

I'll try to verify whether `snp_allele_frequencies()` is definitely not applying site filters, at least in the latest version. (User was on v9.0.1.)

**Comment by leehart** [comment]
Unable to reproduce original issue. `site_mask` setting for `snp_allele_frequencies` appears to be defaulting and working as expected.

Colab notebook demo: https://colab.research.google.com/drive/18WxwCZ5-XBIopWxwwAKo2l-SX-S-fjNg?usp=sharing
