### ISSUE TITLE
Slow import

### ISSUE THREAD

**Issue by alimanfoo** [malariagen/malariagen-data-python#656]
Importing `malariagen_data` is a little slow at the moment, likely because `anjl` is imported internally which triggers jit compilation of `anjl` functions. Perhapse we could move to only importing `anjl` when needed within the neighbour-joining functions.

**Comment by leehart** [comment]
Another complication, encountered when trying to handle the use of `anjl` in function params, is the requirement for parameters to be documented. 🤔

**Comment by leehart** [comment]
Plan to avoid using `anjl.params` by using identical internal params instead.
