### ISSUE TITLE
`test_h12_calibration` has been failing (somewhat) randomly lately

### ISSUE THREAD

**Issue by jonbrenas** [malariagen/malariagen-data-python#680]
In the last few days, `test_h12_calibration` has been failing every now and then. 

<img width="964" alt="Screenshot 2024-12-03 at 15 31 48" src="https://github.com/user-attachments/assets/490eae28-8db7-41ed-8a82-48a843e05989">

**Comment by alimanfoo** [comment]
Hi @jonbrenas, I hit this too, hopefully fixed in https://github.com/malariagen/malariagen-data-python/pull/676/commits/756097aaf84d2570f0b62c051353e587f4c5ef87
