### ISSUE TITLE
Include cohorts in Ag3 sample metadata

### ISSUE THREAD

**Issue by alimanfoo** [malariagen/malariagen-data-python#94]
The cohort metadata are very useful and it would make life easier if they were included with the sample metadata by default, rather than having to separately load and merge the sample metadata and cohort metadata dataframes. To implement this, the following changes could be made:

1. Modify the signature of the `Ag3.sample_metadata()` method to include a `cohorts_analysis` parameter with a default value to the latest cohorts analysis. 
2. Modify the implementation of the `Ag3.sample_metadata()` method to load the cohorts metadata and join it to the general sample metadata, if the `cohorts_analysis` parameter is not None.

Note that a potential problem with doing this is that some future releases may be released before a new cohorts analysis is performed including it. In this case the release would have sample metadata but no cohorts metadata. This could be mitigated by either (a) ensuring we always run a cohorts analysis immediately following each release and before partners are notified, and/or (b) building in some logic to handle missing cohort files.

**Comment by cclarkson** [comment]
Hi @alimanfoo, I think the best thing to do with cohorts metadata is to always generate straight after a release, before informing partners. I feel the benefits outweigh the short delay.

**Comment by alimanfoo** [comment]
> Hi @alimanfoo, I think the best thing to do with cohorts metadata is to always generate straight after a release, before informing partners. I feel the benefits outweigh the short delay.

Hi Chris, yes I'm with you, let's go for that option and see how it works out.
